services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  migrations:
    image: flyway/flyway
    command:
      [
          "-url=jdbc:postgresql://db/",
          "-user=postgres",
          "-password=postgres",
          "-connectRetries=60",
          "migrate",
      ]
    volumes:
      - "./db/sql:/flyway/sql"
    depends_on:
      - db

