services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
  migrations:
    image: flyway/flyway
    command:
      [
          "-url=jdbc:postgresql://db/",
          "-user=postgres",
          "-password=$POSTGRES_PASSWORD",
          "migrate",
      ]
    volumes:
      - "./db/sql:/flyway/sql"
  server:
    build: .
    init: true
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=$POSTGRES_PASSWORD
      - PGDATABASE=postgres
    restart: on-failure