services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
  migrations:
    extends:
      file: docker-compose.common.yml
      service: migrations
    depends_on:
      - db
  server:
    extends:
      file: docker-compose.common.yml
      service: server
    depends_on:
      - db
    ports:
      - "8080:8080"